package customjavafx.scene.control;


public enum BeadRoadResult {
    BANKER_WIN,
    BANKER_WIN_BANKER_PAIR,
    BANKER_WIN_PLAYER_PAIR,
    BANKER_WIN_BOTH_PAIR,
    PLAYER_WIN,
    PLAYER_WIN_BANKER_PAIR,
    PLAYER_WIN_PLAYER_PAIR,
    PLAYER_WIN_BOTH_PAIR,
    TIE_WIN,
    TIE_WIN_BANKER_PAIR,
    TIE_WIN_PLAYER_PAIR,
    TIE_WIN_BOTH_PAIR,
    EMPTY;
}


